development: &default
  adapter: postgresql
  encoding: utf8
  pool: 20
  timeout: 5000
  username: ice
  password: ice123
  host: localhost
  database: match_sync

production: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: match_sync
