development:
  adapter_javascript_url: "https://js.pusher.com/3.0/pusher.min.js"
  app_id: "182187"
  api_key: "bf2c64084b0bbb4fc8be"
  auth_token: "cfba8fa5b8083f80435e"
  adapter: "Pusher"
  async: true

production:
  adapter_javascript_url: "https://js.pusher.com/3.0/pusher.min.js"
  app_id: "182187"
  api_key: "bf2c64084b0bbb4fc8be"
  auth_token: "cfba8fa5b8083f80435e"
  adapter: "Pusher"
  async: true
